services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  
  db:
    image: postgres:16.0
    expose:
      - "5432"
    volumes:
      - postgers_data:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  postgers_data:
  static_volume: